jobs:
  - name: build_develop
    type: runSh
    steps:
      - IN: sample_node_develop
      - TASK:
        - script: printenv
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('

  - name: build_staging
    type: runSh
    steps:
      - IN: sample_node_staging
      - IN: build_develop
      - TASK:
        - script: printenv
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('

  - name: build_master
    type: runSh
    steps:
      - IN: sample_node_master
      - IN: build_staging
      - TASK:
        - script: printenv
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('
