jobs:
  - name: build_develop
    type: runSh
    steps:
      - IN: sample_node_develop
      - TASK:
        - script: cd ./IN/sample_node_develop/gitRepo/
        - script: ./build.sh
#        - script: npm install
#        - script: grunt
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('

  - name: build_staging
    type: runSh
    steps:
      - IN: sample_node_staging
      - IN: build_develop
        switch: off
      - TASK:
        - script: cd ./IN/sample_node_staging/gitRepo/
        - script: npm install
        - script: grunt
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('

  - name: build_master
    type: runSh
    steps:
      - IN: sample_node_master
      - IN: build_staging
        switch: off
      - TASK:
        - script: cd ./IN/sample_node_master/gitRepo/
        - script: npm install
        - script: grunt
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('
